GET http://127.0.0.1:3000

###

POST http://127.0.0.1:3000/token 
Content-Type: application/json

{
  "name": "ADI",
  "symbol": "ADI",
  "type": "ERC20",
  "address": "0x001",
  "decimals": 18
}

###

GET http://127.0.0.1:3000/token

###
GET http://127.0.0.1:3000/token/0x001

###
POST http://127.0.0.1:3000/tx 
Content-Type: application/json

{
  "hash": "0xa3c3e3",
  "dateTime": "2016-05-06T12:45:33",
  "token": "0x001",
  "from": "0xbbaa",
  "to": "0xccdd",
  "amount": "42"
}

###
GET http://127.0.0.1:3000/tx?token=0x001

###
POST http://127.0.0.1:3000/graphql 

#X-Request-Type: GraphQL
Accept: application/json
#Content-Type: application/json
content-type: multipart/form-data
{
  tokens {
    address
  }
}
